Small fixes ... rename index type to index_t to avoid clash on linux:
/usr/include/string.h: In function ‘const char* index(const char*, int)’:
/usr/include/string.h:482:34: error: ‘const char* index(const char*, int)’ redeclared as different kind of symbol
 index (const char *__s, int __c) __THROW